### ISSUE TITLE
Tabel naar voren halen en meer een inhoudsopgave laten zijn

### ISSUE THREAD

**Issue by jauco** [CLARIAH/software-quality-guidelines#10]
@reinierdevalk

**Comment by proycon** [comment]
De huidige opzet in TeX leent zich daar niet echt voor eigenlijk. De items worden gedefinieerd bij hun uitleg en vanuit de tabel wordt daar naar verwezen zodat we geen dubbele tekst hebben, dat omkeren is niet zo triviaal. Misschien toch maar achteraan houden dan?

**Comment by reinierdevalk** [comment]
Daar zat ik ook al mee in mijn maag, inderdaad. Zullen we het voor nu dan
maar zo laten? Voor mij mag ie best achterin blijven, als appendix. Als er
commentaar op komt zien we dat wel bij de volgende versie...

Op 2 juli 2016 10:43 schreef Maarten van Gompel notifications@github.com:

**Comment by jauco** [comment]
ok
