### ISSUE TITLE
Move indicators to e.g. a Google Form

### ISSUE THREAD

**Issue by RinkeHoekstra** [CLARIAH/software-quality-guidelines#14]
I think it would be hugely useful to have a Google Form-version of the criteria. They are currently formulated as a survey or questionnaire. 

Having to print the document, and tick the boxes by hand is not a very sustainable model. Especially if we want to somehow analyze the results (semi) automatically.

**Comment by proycon** [comment]
Agreed, I already wrote a small script to hold the survey from a terminal and output the results in MarkDown (issue #12, so the results can be committed to the software's repository), but I think we need to set up a proper survey website for this (not to keen on using external services like Google Forms).

**Comment by proycon** [comment]
Done, survey is now available on http://applejack.science.ru.nl/clariah-software-quality/

**Comment by reinierdevalk** [comment]
Niiiice!

Een paar hele kleine dingetjes die me opvielen:
-12.7: --> kleine letter i.p.v. hoofdletter (wrs ook in het LaTeX document)
-18: --> haakje sluiten ontbreekt (wrs ook in het LaTeX document)
-helemaal onderaan: --> Jacco i.p.v. Jauco

Groet,
Reinier

2016-07-29 14:26 GMT+02:00 Maarten van Gompel notifications@github.com:

**Comment by proycon** [comment]
Goed gespot! Gefixed!
