### ISSUE TITLE
Similar efforts

### ISSUE THREAD

**Issue by c-martinez** [CLARIAH/software-quality-guidelines#16]
Nice presentation during the CLARIAH tech day!

We had a very quick chat after the presentation. There are definitely a lot of similarities with the escience center software development guidelines:

https://nlesc.gitbooks.io/guide/content/software/software_overview.html
https://nlesc.gitbooks.io/guide/content/software/checklist.html

Might be interesting for you to have a look. Nice to see we are all working along similar lines :-).

**Comment by proycon** [comment]
Thanks! I had indeed come across this earlier, it looks very good and comprehensive. I think we have a good overlap already, but we should take a deeper look at these to check whether we have any gaps and can adopt some of your items.

**Comment by c-martinez** [comment]
Do let me know if you would like to get in touch with someone at the center to discuss about guidelines.
