### ISSUE TITLE
Open vs closed questions for the indicators

### ISSUE THREAD

**Issue by proycon** [CLARIAH/software-quality-guidelines#2]
All indicators are currently closed questions that are all to be answered affirmatively.  Some comments we got:
- checklist is now yes/no/no available; [...]  For the time being the questions are made more closed. DSA operates with more open questions, legitimate your efforts.

From my point of view, the argument for closed questions is one of easier measurability, if all questions have to be answered affirmatively it's relatively easy to compute a score for each dimension and for the whole. It would make it easy to transform into a survey form as well.

**Comment by jauco** [comment]
We're going to add open questions + likert scales

**Comment by proycon** [comment]
I propose the following scale to indicate the level of compliance with each guideline, it will require a bit of interpretation per question:
- 0) No
- 1) Minimal
- 2) Adequate
- 3) Good
- 4) Perfect

We'll have to adjust the measurement formula as well, to that effect, the numbers represent a score that will count towards the total.

**Comment by jauco** [comment]
Seems good to me. But there is a lot of literature/research on likerts
scales so I suggest a quick google on likert scale labels.

**Comment by rlzijdeman** [comment]
did you discuss whether to go fo a categorical or continuous scale?

Best,

## Richard

Dr. R.L. Zijdeman | CDO | International Institute of Social History | Cruquiusweg 31 | 1019 AT Amsterdam | +31 20 668 5 866

On 01 Jul 2016, at 14:44, Jauco Noordzij <notifications@github.com<mailto:notifications@github.com>> wrote:

Seems good to me. But there is a lot of literature/research on likerts
scales so I suggest a quick google on likert scale labels.

**Comment by proycon** [comment]
We didn't really consider a continuous scale, I do think discrete is more common and easier to interpret. We're moving from a Yes/No system to a five-point Likert scale to allow for more flexibility in the responses. For some questions, this flexibility feels a bit constrained though. Most important is that all the options in the scale are at equal distance, which I hope the proposed scale accomplishes. "Minimal" should be interpreted bad compliance to a certain guideline, although better than "No", whereas "adequate", the central option, is a close pass.

**Comment by proycon** [comment]
I'm assuming our current solution is accepted now and closing this.
