### ISSUE TITLE
Consumer vs developer perspective

### ISSUE THREAD

**Issue by proycon** [CLARIAH/software-quality-guidelines#5]
We have to strike a balance between a consumer and developer perspective. This was worded nicely in the following comment:

> The guidelines are envisioned from a consumer point of view. There is nothing wrong with that, but the document lacks an explicit statement that it is envisioned from this viewpoint and there should be a justification for doing so. After all, CLARIAH is
> a consumer, but also a producer of software.  
> Why is the document consumer centric? Indications are that the words architecture and/or design are very sparse in the document. Architecture pops up 2 times, design 3 times, one time in conjuncture with architecture. A consumer centric approach looks  
> at software, ‘the thing that is’; a producer centric approach looks at software as the thing that is the result of a process in which architecture and design play a prominent role.

**Comment by jauco** [comment]
@reinierdevalk  dit meenemen in de intro

**Comment by reinierdevalk** [comment]
Provisorisch opgelost - zie TODO-rdv in tex document. Kan hopelijk dicht nu?
