### ISSUE TITLE
More attention for deployment solutions like Vagrant, Ansible, Docker

### ISSUE THREAD

**Issue by proycon** [CLARIAH/software-quality-guidelines#6]
We received the following comment:

> This chapter lacks more recent developments in installing and deploying software on server-like machines with automated build- and install scripts.  Vagrant, Ansible, Docker cannot be missed when it comes to deploying software.

**Comment by jauco** [comment]
docker and vagrant should receive more attention then ansible. because they are more of a de facto standard within clariah projects

**Comment by proycon** [comment]
I added a criterion to address this (IS10) now. Should solve this issue (but checking appreciated!).
